# https://taskfile.dev

version: '3'

vars:
  NAME: 'httptemplate'

tasks:
  clean:
    cmds:
      - go clean

  test:
    desc: "runs unit tests"
    cmds:
      - go test -v ./...
  
  format:
    cmds:
      - gofmt -s -w .
    sources:
      - ./**/*.go

  lint:
    cmds:
      - cmd: golangci-lint run -v -c ./.golangci.yml
        ignore_error: true
    sources:
      - ./**/*.go
